name: tests

on:
  push:
    branches: ["main"]

jobs:
  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3
      # Build the image
      - run: docker build . -t sketch-editor
